Le monde 'inOrder' diffère:
inOrder(1,2,1,false) returned Ce test a levé une exception scala.MatchError : (1,2,1,false) (of class scala.Tuple4) while false were expected.

